### ISSUE TITLE
Expose entire EntryModel instead of just Title and URL

### ISSUE THREAD

**Issue by RobErskine** [wja-no/craft-weighted-search#2]
Hey there, 

Great plugin, you're savin' my butt a lot of time. 

Was just curious about the `$result` array in the `substringSearch` function `WeightedSearch_EntriesService.php`:

``` php
$result[$viewableId] = array(
   'title' => $viewableEntry->title,
   'url' => $viewableEntry->url,
   'excerpt' => '',
   'score' => ($overrideWeight + $weight),
);
```

Was there a reason why you're only abstracting out the `title` and `url` from the original EntryModel? 

Couldn't you just expose the entire EntryModel?

``` php
$result[$viewableId] = array(
   'entry' => $viewableEntry,
   'score' => ($overrideWeight + $weight),
);
```

Templating could then look like this:

``` php
 {% set query = craft.request.getParam('q') %}
 {% set results = craft.weightedSearch.substringSearch(query) %}
 {% if results %}
     <ul>
         {% for searchResult in results %}
             <li>
                <a href="{{ searchResult.entry.url }}">{{ searchResult.entry.title }}</a>
                <img src="{{searchResult.entry.thumbnail.first().url}}"> 
                <p>{{ searchResult.entry.excerpt|raw }}</p>
                <!-- Score: {{ searchResult.score }} -->
             </li>
         {% endfor %}
     </ul>
 {% else %}
     <p>{{ "No results"|t }}</p>
 {% endif %}
```

^ Meaning that you could expose whatever you wanted in the search result, like images or other fields.

**Comment by oyvind-stenhaug** [comment]
Hi! It's been a while since I wrote it, so I'm not sure, but I think the only reason might be that I didn't find any documentation anywhere suggesting that this would work.

It does indeed sound like a good idea!

**Comment by RobErskine** [comment]
Oh, very cool! If you're up for it I'd be up to updating the service and updating the documentation to reflect this change, if you'd be into it?

**Comment by oyvind-stenhaug** [comment]
Sure, pull requests are welcome!
