### ISSUE TITLE
Excerpts Not Working

### ISSUE THREAD

**Issue by houdini3009** [wja-no/craft-weighted-search#7]
None of the results shown on my search results page has an excerpt. Every excerpt is a string with 0 length. Am I missing a step beyond installing the plugin and utilizing the template tags as described in the README?

**Comment by oyvind-stenhaug** [comment]
Those should be the only steps necessary (assuming that all entries found have URLs, but that's not really related to excerpts). But unfortunately the excerpts functionality currently doesn't work for all field types. I should probably mention this in the documentation.

Specifically, it should work when finding something in a `PlainText` and/or `RichText` field. But other field types aren't quite so easy, notably `Matrix`.

The code is currently able to get to the entry containing the (real, non-searchindex-"normalized") text, and to the field handle of the field. For simple fields it's just a matter of doing `$entry[$fieldHandle]` to get the value, but a matrix probably contains multiple blocks of various block types.

**Comment by houdini3009** [comment]
Yeah, that's the issue - the content is in a Matrix field. That makes sense. Thanks!
